# Example ESPHome configuration using the Marstek BLE Gateway package
# 
# This shows how to integrate the Marstek BLE Gateway into your own ESP32 device

esphome:
  name: marstek
  friendly_name: marstek

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/tWzgpNXUm9lLMOXV+gO1J6wmZrRjXE1iOKgafwCoh4="

ota:
  - platform: esphome
    password: "6dc67d82417a1d1be26d7f86fdf0b463"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Marstek Fallback Hotspot"
    password: "7ubfReHhmeJI"

captive_portal:

time:
  - platform: homeassistant
    id: ha_time

packages:

  remote_package_shorthand: github://Marca2005/marstek-ble-gateway/marstek-ble-gateway.yaml

  remote_package_files:
    url: https://github.com/Marca2005/marstek-ble-gateway
    files: marstek-ble-gateway.yaml
    refresh: 0d
